# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-23 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0019_auto_20180605_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitmilestone',
            name='excluded_file_patterns',
            field=models.CharField(blank=True, default=b'*/.* *.class *.jar *.o *.obj *.lib *.pyc', help_text=b'Filename patterns to exclude from upload, separated by whitespace', max_length=300),
        ),
    ]
