# Generated by Django 2.1 on 2019-05-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0020_auto_20180823_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='class_type',
            field=models.CharField(blank=True, choices=[('ENUM', 'enum'), ('EXCE', 'exception'), ('TEST', 'test'), ('NONE', 'none')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('U', 'User'), ('S', 'Static analysis'), ('T', 'Test result')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('S', 'student'), ('T', 'teacher'), ('V', 'volunteer')], max_length=1),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='allow_unextending_to_past',
            field=models.BooleanField(default=False, help_text="If enabled, then user can give back extension days even if it pushes their deadline back into the past. If disabled, then user's deadline must always be in the future after a change."),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='type',
            field=models.CharField(choices=[('S', 'Submit'), ('R', 'Review')], max_length=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='reason',
            field=models.CharField(blank=True, choices=[('S', 'Summary'), ('R', 'Received reply'), ('C', 'Received comment on submission')], max_length=1),
        ),
        migrations.AlterField(
            model_name='reviewmilestone',
            name='reveal_date',
            field=models.DateTimeField(blank=True, help_text='When comments are revealed to code author. If blank, comments are always visible to author.', null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='description',
            field=models.CharField(blank=True, help_text='Subject Name. (ex.) Software Construction', max_length=140),
        ),
        migrations.AlterField(
            model_name='semester',
            name='is_current_semester',
            field=models.BooleanField(default=False, verbose_name='Is in progress'),
        ),
        migrations.AlterField(
            model_name='submitmilestone',
            name='excluded_file_patterns',
            field=models.CharField(blank=True, default='*/.* *.class *.jar *.o *.obj *.lib *.pyc', help_text='Filename patterns to exclude from upload, separated by whitespace', max_length=300),
        ),
        migrations.AlterField(
            model_name='submitmilestone',
            name='included_file_patterns',
            field=models.CharField(blank=True, default='*.java *.c *.h *.cpp *.CC *.py', help_text='Filename patterns to upload, separated by whitespace; e.g. *Foo*.java matches Foo.java and src/TheFool/Bar.java', max_length=300),
        ),
        migrations.AlterField(
            model_name='submitmilestone',
            name='restrict_access',
            field=models.BooleanField(default=False, help_text="If enabled, restrict who can view the students' chunks to the student authors and any assigned reviewers. LAs and TAs will not be able to view submissions if this is enabled."),
        ),
        migrations.AlterField(
            model_name='submitmilestone',
            name='run_checkstyle',
            field=models.BooleanField(default=False, help_text="If enabled, runs Checkstyle on the students' Java code, and preloads its output as comments in Caesar"),
        ),
        migrations.AlterField(
            model_name='submitmilestone',
            name='starting_code_path',
            field=models.CharField(blank=True, default='', help_text='Folder containing starting code for the assignment.  Should contain one subfolder, usually called staff/, under which is the starting code.', max_length=300),
        ),
        migrations.AlterField(
            model_name='submitmilestone',
            name='submitted_code_path',
            field=models.CharField(blank=True, default='', help_text='Folder containing student code for the assignment. Should contain subfolders named by student usernames: abc/, def/, ghi/, etc.', max_length=300),
        ),
        migrations.AlterField(
            model_name='submitmilestone',
            name='suppress_checkstyle_regex',
            field=models.CharField(blank=True, default='', help_text='Regex of checkstyle comments to suppress; separate multiple patterns by |', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('O', 'Opened'), ('C', 'Completed'), ('U', 'Unfinished')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(choices=[(1, '+1'), (-1, '-1')]),
        ),
    ]
